### ISSUE TITLE
There is no 'weighted_loss' in logs on batch end

### ISSUE THREAD

**Issue by NaivePawn** [LIBOL/ODL#2]
def on_batch_end(self, batch, logs = {}):
self.l.append(logs.get('loss'))
if self.hedge:
self.acc.append(logs.get('weighted_acc'))
else:
self.acc.append(logs.get('acc'))

**Comment by NaivePawn** [comment]
def on_batch_end(self, batch, logs = {}):
        self.l.append(logs.get('loss'))
        if self.hedge:
            self.acc.append(logs.get('weighted_acc'))
        else:
            self.acc.append(logs.get('acc'))

**Comment by phquang** [comment]
Hi, "weighted_loss" after each sample is stored in self.l by calling logs.get('loss') .

**Comment by NaivePawn** [comment]
Sorry, not "weight_loss", there is no "weighted_acc" in logs on batch end

**Comment by phquang** [comment]
"weighted_acc" is calculated automatically by keras when you compile the model with "hedge" argument set to True (see ODL/src/hbp/main.py line 99), without hedge, keras will calculate the normal accuracy, therefore on_batch_end will log the corresponding accuracy with respect to the hedge argument.
