### ISSUE TITLE
tensorflow version issue

### ISSUE THREAD

**Issue by jianhaod** [LIBOL/ODL#3]
sorry, could you show me the tensorflow version env?
because i catch a error, when use repo dataset and code, i can;t reproduce HPB training demo.

    model.compile(optimizer = optim, loss = loss_dict, hedge = config['hedge'],loss_weights = loss_weights, metrics = ['accuracy'])
  File "/usr/local/python27/lib/python2.7/site-packages/keras/engine/training.py", line 684, in compile
    total_loss = K.sum(K.dot(self.holder, self.metrics_tensors))
  File "/usr/local/python27/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 790, in dot
    if ndim(x) is not None and (ndim(x) > 2 or ndim(y) > 2):
  File "/usr/local/python27/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 396, in ndim
    dims = x.get_shape()._dims
AttributeError: 'list' object has no attribute 'get_shape'

it seems an tensorflow error
i use keras version as repo show and backend tensorflow i use 1.2.0

**Comment by phquang** [comment]
Hi, this repo was developed and tested with keras 1 and theano backend only,  you may try to install the correct dependencies' version.

**Comment by jianhaod** [comment]
ok, i know that, this repo use theano backend, it seems not support tensorflow backend, and it also will have some issue with several python package dependencies, for example python env 2.7 or 3.x and numpy, theano,  kears etc, all those dependencies version should match specific versions, i will fix those problem in my environment, thanks a lot

**Comment by ZXisSpider** [comment]
> ok, i know that, this repo use theano backend, it seems not support tensorflow backend, and it also will have some issue with several python package dependencies, for example python env 2.7 or 3.x and numpy, theano, kears etc, all those dependencies version should match specific versions, i will fix those problem in my environment, thanks a lot

Have you succeeded in installing the right dependencies?
