### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by q138ben** [LIBOL/ODL#5]
Hi, I have installed the dependency of Theano 0.8.2 and Keras 1.2.1 and replaced Keras's keras/engine/training.py file with the modified training.py.  Then when I try to run the main.py, there is error regarding tensorflow though you mentioned in the previous issues that you did not use tensorflow backend.

It looks like the tensorflow was automatically imported when keras was imported. So I guess I should install one more dependency of tensorflow. But which version of tensorflow did you use? 

(onlineDL) E:\ODL\src\hbp>python main.py -c hb19.yaml
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from keras.datasets import mnist
  File "E:\miniconda3_64\envs\onlineDL\lib\site-packages\keras\__init__.py", line 4, in <module>
    from . import engine
  File "E:\miniconda3_64\envs\onlineDL\lib\site-packages\keras\engine\__init__.py", line 10, in <module>
    from .training import Model
  File "E:\miniconda3_64\envs\onlineDL\lib\site-packages\keras\engine\training.py", line 20, in <module>
    from .. import optimizers
  File "E:\miniconda3_64\envs\onlineDL\lib\site-packages\keras\optimizers.py", line 9, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow

**Comment by phquang** [comment]
Hi, thanks for your interest in our work. 
This is an older project and many dependencies have been upgraded in our server since then. According to our logs, you can try installing tensorflow version 1.4.1 or 0.9.0. Alternatively, you can try an unofficial pytorch implementation provided here: https://github.com/alison-carrera/onn

**Comment by q138ben** [comment]
Hi, thx for the prompt reply. I am moving to the pytorch implementation now.  But when I was trying to install onn, something went wrong with the torch installation. My environment is clean. Which torch version do you use? Or could you please provide a thorough list of all the required dependency? Many thanks.

(onn) E:\ODL\src\hbp>pip install --upgrade onn
Collecting onn
  Using cached onn-0.2.1.tar.gz (4.5 kB)
Collecting numpy
  Downloading numpy-1.19.1-cp36-cp36m-win_amd64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 6.4 MB/s
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Collecting mabalgs
  Using cached mabalgs-0.6.4.tar.gz (8.9 kB)
Collecting pyyaml
  Using cached PyYAML-5.3.1-cp36-cp36m-win_amd64.whl (215 kB)
Building wheels for collected packages: onn, torch, mabalgs
  Building wheel for onn (setup.py) ... done
  Created wheel for onn: filename=onn-0.2.1-py3-none-any.whl size=4693 sha256=773a5d46b45269987346a8f36fd8ff08ee72d931838a6a115225bfd166234710
  Stored in directory: c:\users\binbi\appdata\local\pip\cache\wheels\03\25\bc\b315b926604dccf94c6be6e0f3c5217a7b989e54f499a26310
  Building wheel for torch (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'E:\miniconda3_64\envs\onn\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\binbi\AppData\Local\Temp\pip-wheel-au4yz2oz'
       cwd: C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\setup.py", line 265, in <module>
      description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
    File "E:\miniconda3_64\envs\onn\lib\site-packages\setuptools\__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "E:\miniconda3_64\envs\onn\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "E:\miniconda3_64\envs\onn\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "E:\miniconda3_64\envs\onn\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "E:\miniconda3_64\envs\onn\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "E:\miniconda3_64\envs\onn\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'E:\miniconda3_64\envs\onn\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
  Building wheel for mabalgs (setup.py) ... done
  Created wheel for mabalgs: filename=mabalgs-0.6.4-py3-none-any.whl size=9695 sha256=de92cb104fb640594c41bcd94989213de69de159bd22a75636a14d887bc9d33f
  Stored in directory: c:\users\binbi\appdata\local\pip\cache\wheels\c7\46\82\447a0fea34b7309f72a44fdf0d9d2881a281c4ed7586315154
Successfully built onn mabalgs
Failed to build torch
DEPRECATION: Could not build wheels for torch which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: numpy, pyyaml, torch, mabalgs, onn
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'E:\miniconda3_64\envs\onn\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\binbi\AppData\Local\Temp\pip-record-j6c9nas6\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\miniconda3_64\envs\onn\Include\torch'
         cwd: C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\setup.py", line 265, in <module>
        description="Tensors and Dynamic neural networks in Python with strong GPU acceleration",
      File "E:\miniconda3_64\envs\onn\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "E:\miniconda3_64\envs\onn\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "E:\miniconda3_64\envs\onn\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "E:\miniconda3_64\envs\onn\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\binbi\AppData\Local\Temp\pip-install-niqd1rlm\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'E:\miniconda3_64\envs\onn\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\binbi\\AppData\\Local\\Temp\\pip-install-niqd1rlm\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\binbi\AppData\Local\Temp\pip-record-j6c9nas6\install-record.txt' --single-version-externally-managed --compile --install-headers 'E:\miniconda3_64\envs\onn\Include\torch' Check the logs for full command output.

**Comment by q138ben** [comment]
The pytorch implementation is working. Thanks.
